apiVersion: apps/v1
kind: Deployment
metadata:
  name: wisecow-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wisecow
  template:
    metadata:
      labels:
        app: wisecow
    spec:
      containers:
      - name: wisecow-container
        image: ***.dkr.ecr.us-east-1.amazonaws.com/mapup-repo:latest
        command: ["/bin/bash", "-c", "./wisecow.sh"]
        ports:
        - containerPort: 4499
