name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.ECR_REPO }}:$GITHUB_SHA .
          docker login -u AWS -p $(aws ecr get-login-password --region us-east-1) ${{ secrets.ECR_REPO }}
        env:
          REPOSITORY: mapup-repo
          IMAGE_TAG: latest

      - name: Image Push
        run:  docker push ${{ secrets.ECR_REPO }}:$GITHUB_SHA

      - name: Deploy to Kubernetes
        if: github.ref == 'refs/heads/main'
        run: |
          kubectl apply -f deployment.yaml --validate=false
          kubectl apply -f service.yaml

